/* =========================================================
    API Gateway Jenkins Pipeline
 =========================================================*/

pipeline {
    agent none

    options {
        timestamps()
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '10'))
    }

    environment {
        DOCKERHUB_USER = "lakshvar96"
        IMAGE = "api-gateway"
    }

    stages {

        // -------------------------------
        stage('Checkout Code') {
            agent { label 'workernode1' }
            steps {
                checkout scm
            }
        }

        // -------------------------------
        stage('Stash Source') {
            agent { label 'workernode1' }
            steps {
                stash includes: '**/*', name: 'source-code'
            }
        }

        // -------------------------------
        stage('Build & Test') {
            agent { label 'workernode2' }
            steps {
                unstash 'source-code'
                dir('api-gateway') {
                    sh 'mvn clean install -DskipTests=false'
                }
            }
        }

        // -------------------------------
        stage('Docker Build') {
            agent { label 'workernode3' }
            steps {
                unstash 'source-code'
                dir('api-gateway') {
                    sh """
                    docker build -t ${DOCKERHUB_USER}/${IMAGE}:${BUILD_NUMBER} .
                    docker tag ${DOCKERHUB_USER}/${IMAGE}:${BUILD_NUMBER} ${DOCKERHUB_USER}/${IMAGE}:latest
                    """
                }
            }
        }

        

        // -------------------------------
        stage('Push Docker Image') {
            agent { label 'workernode3' }
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                }
                sh """
                docker push ${DOCKERHUB_USER}/${IMAGE}:${BUILD_NUMBER}
                docker push ${DOCKERHUB_USER}/${IMAGE}:latest
                """
            }
        }
    }

    post {
        success { echo "✅ API Gateway Pipeline SUCCESS" }
        failure { echo "❌ API Gateway Pipeline FAILED" }
    }
}
