/* =========================================================
    Frontend Web App Jenkins Pipeline
 =========================================================*/

pipeline {
    agent none

    options {
        timestamps()
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '10'))
    }

    environment {
        DOCKERHUB_USER = "lakshvar96"
        IMAGE = "frontend"
        SONAR = "frontend" // Jenkins SonarQube server name
    }

    stages {

        // -------------------------------
        stage('Checkout Code') {
            agent { label 'workernode1' }
            steps {
                checkout scm
            }
        }

        // -------------------------------
        stage('Stash Source') {
            agent { label 'workernode1' }
            steps {
                stash includes: '**/*', name: 'source-code'
            }
        }

        
        // -------------------------------
        stage('Docker Build') {
            agent { label 'workernode3' }
            steps {
                unstash 'source-code'
                dir('web-application') { // Dockerfile should be here
                    sh """
                    docker build -t ${DOCKERHUB_USER}/${IMAGE}:${BUILD_NUMBER} .
                    docker tag ${DOCKERHUB_USER}/${IMAGE}:${BUILD_NUMBER} ${DOCKERHUB_USER}/${IMAGE}:latest
                    """
                }
            }
        }

        // -------------------------------
        stage('Trivy Scan') {
            agent { label 'workernode3' }
            steps {
                sh """
                # Scan for HIGH and CRITICAL vulnerabilities
                trivy image --exit-code 1 --severity HIGH,CRITICAL ${DOCKERHUB_USER}/${IMAGE}:${BUILD_NUMBER}
                """
            }
        }

        // -------------------------------
        stage('Push Docker Image') {
            agent { label 'workernode3' }
            steps {
                unstash 'source-code'
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                }
                sh """
                docker push ${DOCKERHUB_USER}/${IMAGE}:${BUILD_NUMBER}
                docker push ${DOCKERHUB_USER}/${IMAGE}:latest
                """
            }
        }
    }

    post {
        success { echo "✅ Frontend Pipeline SUCCESS" }
        failure { echo "❌ Frontend CI Pipeline FAILED" }
    }
}
