/* =========================================================
    web app repo -frontend
 =========================================================*/

 pipeline {
    agent none

    options {
        timestamps()
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '10'))
    }

    environment {
        DOCKERHUB_USER = "lakshvar96"
        IMAGE = "frontend"
        SONAR = "frontend" // Jenkins SonarQube server name
    }

    stages {

        stage('Checkout Code') {
            agent { label 'workernode1' }
            steps {
                checkout scm
            }
        }

        stage('Stash Source') {
            agent { label 'workernode1' }
            steps {
                stash includes: '**/*', name: 'source-code'
            }
        }

              

        stage('SonarQube Analysis') {
            agent { label 'workernode2' }
            steps {
                unstash 'source-code'
                script {
                    def branch = env.BRANCH_NAME ?: "main"
                    withSonarQubeEnv("${SONAR}") {
                        dir('web-application') {
                            sh """
                            npm install
                            ${scannerHome}/bin/sonar-scanner \
                            -Dsonar.projectKey=frontend \
                            -Dsonar.projectName=frontend \
                            
                            -Dsonar.sources=src \
                            
                            -Dsonar.exclusions=**/node_modules/**,**/build/**
                            """
                        }
                    }
                }
            }
        }

        stage('Quality Gate') {
            agent { label 'workernode2' }
            steps {
                timeout(time: 2, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Docker Build') {
            agent { label 'workernode3' }
            steps {
                unstash 'source-code'
                dir('service-one') {
                    sh """
                    docker build -t ${DOCKERHUB_USER}/${IMAGE}:${BUILD_NUMBER} .
                    docker tag ${DOCKERHUB_USER}/${IMAGE}:${BUILD_NUMBER} ${DOCKERHUB_USER}/${IMAGE}:latest
                    """
                }
            }
        }

        stage('Trivy Scan') {
            agent { label 'workernode3' }
            steps {
                sh """
                trivy image --exit-code 0 --severity HIGH,CRITICAL ${DOCKERHUB_USER}/${IMAGE}:${BUILD_NUMBER}
                """
            }
        }

        stage('Push Docker Image') {
            agent { label 'workernode3' }
            steps {
                unstash 'source-code'
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                }
                sh """
                docker push ${DOCKERHUB_USER}/${IMAGE}:${BUILD_NUMBER}
                docker push ${DOCKERHUB_USER}/${IMAGE}:latest
                """
            }
        }
    }

    post {
        success { echo "✅ fronetend Pipeline SUCCESS" }
        failure { echo "❌ fronetend CI Pipeline FAILED" }
    }
}
